AWSTemplateFormatVersion: '2010-09-09'
Description: VPC and S3 Bucket

Resources:

  Hub1-Ingress-PRD-IND:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Hub1-Ingress-PRD-IND

  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: avaya-datastore-prd-ind   # change to unique name